/**
 * nicknames.js
 * Diccionario precargado de apodos para los números del 1 al 75.
 * El Admin puede sobrescribir cualquier apodo en tiempo real vía evento update_nickname.
 * Este archivo es la fuente de verdad inicial; los cambios en runtime viven en Room.nicknames.
 */

const DEFAULT_NICKNAMES = {
    1: 'El as de espadas',
    2: 'El patito',
    3: 'El niño bonito',
    4: 'Las cuatro estaciones',
    5: 'El cinco de oros',
    6: 'Media docena',
    7: 'El siete y medio',
    8: 'Los bigotes del gato',
    9: 'El número de la suerte',
    10: 'La decena',
    11: 'Las piernas de la señorita',
    12: 'La docena',
    13: 'La docena y uno',
    14: 'El catorce',
    15: 'La quincena',
    16: 'Sweet sixteen',
    17: 'El diecisiete',
    18: 'La mayoría de edad',
    19: 'El diecinueve',
    20: 'Las dos decenas',
    21: 'La edad del pavo',
    22: 'Los patitos',
    23: 'El veintitrés',
    24: 'Dos docenas',
    25: 'Las bodas de plata',
    26: 'El veintiséis',
    27: 'El veintisiete',
    28: 'Los dientes del tiburón',
    29: 'El veintinueve',
    30: 'Las tres decenas',
    31: 'El treinta y uno',
    32: 'Los dientes de leche',
    33: 'Las dos emes',
    34: 'El treinta y cuatro',
    35: 'El treinta y cinco',
    36: 'El treinta y seis',
    37: 'El treinta y siete',
    38: 'El treinta y ocho',
    39: 'El treinta y nueve',
    40: 'Las cuatro decenas',
    41: 'El cuarenta y uno',
    42: 'La respuesta al universo',
    43: 'El cuarenta y tres',
    44: 'Las cuatro eles',
    45: 'El cuarenta y cinco',
    46: 'El cuarenta y seis',
    47: 'El cuarenta y siete',
    48: 'El cuarenta y ocho',
    49: 'El cuarenta y nueve',
    50: 'Las cinco decenas',
    51: 'El cincuenta y uno',
    52: 'Las cartas de la baraja',
    53: 'El cincuenta y tres',
    54: 'El cincuenta y cuatro',
    55: 'Las dos eses',
    56: 'El cincuenta y seis',
    57: 'El cincuenta y siete',
    58: 'El cincuenta y ocho',
    59: 'El cincuenta y nueve',
    60: 'Las seis decenas',
    61: 'El sesenta y uno',
    62: 'El sesenta y dos',
    63: 'El sesenta y tres',
    64: 'El sesenta y cuatro',
    65: 'La jubilación',
    66: 'Las dos jotas',
    67: 'El sesenta y siete',
    68: 'El sesenta y ocho',
    69: 'Los enamorados',
    70: 'Las siete decenas',
    71: 'El setenta y uno',
    72: 'El setenta y dos',
    73: 'El setenta y tres',
    74: 'El setenta y cuatro',
    75: 'El último',
};

module.exports = { DEFAULT_NICKNAMES };
